### PR TITLE
Serve static files directly using nginx.

### PR DESCRIPTION
**Pull request by asafpm**

### CODE REVIEW

**Comment by AntonPiccardoSelg** [comment]
@asafpm Is there a way to test it?

**Comment by asafpm** [comment]
adding `--log-level debug` as an argument for gunicorn you can see who serves what content. I don't know if this could be integrated into the development configuration.

**Comment by AntonPiccardoSelg** [comment]
@asafpm Thanks. I will check it later. Yes, I think that would be good to integrate that into the dev configuration :+1:

**Comment by AntonPiccardoSelg** [comment]
Looking in `console` of the browser, it seems that there is still a problem loading `Bootstrap`

**Comment by asafpm** [comment]
Are you sure you are using the new configuration?

I tested with both firefox and chrome and didn't find any loading errors. Does the debug-level log say that web is serving the static files or is it nginx?

**Review by AntonPiccardoSelg — APPROVED** [review]
I see:
>nginx_1  | 172.19.0.1 - - [15/Jun/2017:18:41:33 +0000] "GET /static/bootstrap/js/jquery.min.js HTTP/1.1" 404 233 "http://localhost/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/58.0.3029.110 Chrome/58.0.3029.110 Safari/537.36" "-"

which indicates that nginx is serving the static files. :+1:

**Comment by asafpm** [comment]
I think something is not quite right yet that 404 error in the log already showed up when the static stuff was getting served by flask. Did you add `--log-level debug` to gunicorm? I suspect you still have to rebuild this to get the updated configuration to work.

**Pull request merged**
